vich_uploader:
    db_driver: orm

    mappings:
        product_image:
            uri_prefix:         '%app.posts_images%'
            upload_destination: '%kernel.project_dir%/public%app.posts_images%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_remove: true
